# Generated by Django 3.2.10 on 2022-03-26 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='追加日時')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='タイトル')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='著者')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='説明文')),
                ('published', models.DateField(blank=True, null=True, verbose_name='出版日')),
                ('thumbnail', models.URLField(blank=True, null=True, verbose_name='サムネイル')),
                ('info', models.URLField(blank=True, null=True, verbose_name='詳細情報')),
            ],
        ),
    ]
